<?php echo $this->headTitle('Все альбомы') ?>
<section>
	<h1>Все альбомы</h1>
	<?php if (count($this->albums) != 0) : ?>
	<table class="table table-bordered">
    <thead>
		<td>Обложка</td>
        <td>Название</td>
        <td>Краткое описание</td>
        <td>Фотограф</td>
        <td>Информация</td>
        <td>Управление</td>
        <?php foreach ($this->albums as $album) : ?>
            <tr>
				<td>
					<?php if (!empty($covers[$album->getId()])) : ?>
						<img src="<?php echo '/images/250_' . $covers[$album->getId()]; ?>">
					<?php endif; ?>
				</td>
                <td>
                    <a href="<?php echo $this->url($this->route, ['controller' => 'album', 'action' => 'view', 'id' => $album->getId()], [], false); ?>">
                        <?php echo $album->getName(); ?>
                    </a>
                </td>
                <td>
                    <?php echo $album->getDescription(); ?>
                </td>
                <td>
                    <?php echo $album->getPhotographer(); ?>
                </td>
                <td>
                    Количество фотографий: <?php echo $album->getCountPhoto(); ?>
                    <br>
					<?php if ($album->getCountPhoto() > 0) : ?>
						Последняя фотография: <?php echo $album->getLastUploadPhoto() ?>
					<?php endif; ?>
                </td>
                <td>
                    <a href="<?php echo $this->url($this->route, ['controller' => 'album', 'action' => 'edit', 'id' => $album->getId()], [], false); ?>">Редактировать</a>
                    |
                    <a href="<?php echo $this->url($this->route, ['controller' => 'album', 'action' => 'delete', 'id' => $album->getId()], [], false); ?>">Удалить</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </thead>
	</table>
	<?php endif; ?>
    <a href="<?php echo $this->url('album', ['action' => 'create'], [], false); ?>">
        <button type="button" class="btn btn-primary">Добавить альбом</button>
    </a>
	<?php if (count($this->albums) != 0) : ?>
		<a href="<?php echo $this->url('photo', ['action' => 'add'], [], false); ?>">
			<button type="button" class="btn btn-primary">Добавить фотографию в галерею</button>
		</a>
	<?php endif; ?>
</section>