Module: Gallery
Controller: Album
Action: view

<section>
	<h1>Просмотр альбома</h1>
	<a href="<?php echo $this->url('photo', ['action' => 'add', 'id' => $albumId]) ?>">
		<button type="button" class="btn btn-primary">Добавить фотографию</button>
	</a>
	<br>
	<?php $i = 0 ?>
	<?php foreach ($photos as $photo) : ?>
		<?php ++$i; ?>
		<br>
		<!--<img src="<?php // echo '/images/' . $photo->getFile(); ?>">-->
		<a href="<?php echo '/images/' . $photo->getFile(); ?>" data-lightbox="roadtrip">
			<img src="<?php echo '/images/' . $photo->getFile(); ?>" width="200">
		</a>
	<?php endforeach; ?>
</section>